### PR TITLE
Add MacPorts installation instructions

### PR DESCRIPTION
**Pull request by herbygillot**
https://ports.macports.org/port/git-credential-oauth/

### CODE REVIEW

**Comment by hickford** [comment]
Fantastic, thank you

**Comment by herbygillot** [comment]
Much appreciated.

**Comment by hickford** [comment]
@herbygillot Might you be interested in packaging sister project https://github.com/hickford/git-credential-azure ?

**Comment by herbygillot** [comment]
> @herbygillot Might you be interested in packaging sister project https://github.com/hickford/git-credential-azure ?

Yes. I've just added the port for it. Its info page is available here: https://ports.macports.org/port/git-credential-azure/

**Comment by hickford** [comment]
@herbygillot Brilliant, thank you very much

**Pull request merged**
